#!/bin/bash

echo "burnup notifications:"

mkdir -p /home/rocky/tmp/kprice/tapisrc1-primary-data/notifications
mkdir -p /home/rocky/tmp/kprice/tapisrc1-primary-data/notifications/postgres

python3 ../admin/util/parse_skexport -c notifications -d /home/rocky/tmp/kprice/tapisrc1-primary-data

docker compose up -d
