
networks:
  tapis:
    name: tapis
    external: true


services:

  notifications-api:
    container_name: notifications-api
    image: tapis/notifications:1.6.2 
    environment:
      - TAPIS_SITE_ID=tacc
      - TAPIS_TENANT_SVC_BASEURL=https://admin.rc1.tapis.io
      - TAPIS_DB_JDBC_URL=jdbc:postgresql://notifications-postgres:5432/tapisntfdb
      - TAPIS_DB_USER=tapis_ntf
      - TAPIS_QUEUE_HOST=notifications-rabbitmq
      - TAPIS_QUEUE_ADMIN_USER=tapis
      - TAPIS_QUEUE_USER=notif
    env_file:
      - /home/rocky/tmp/kprice/tapisrc1-primary-data/notifications/env
    networks: 
      - tapis
    depends_on:
      notifications-postgres:
        condition: service_healthy
      notifications-rabbitmq:
        condition: service_healthy
    command: java -Xms1g -Xmx4g --add-opens java.base/java.lang=ALL-UNNAMED --add-opens java.base/java.time=ALL-UNNAMED --add-opens java.base/java.util=ALL-UNNAMED -cp "notifications.jar:dependencies/*" edu.utexas.tacc.tapis.notifications.api.NotificationsApplication
    ports: 
      - "8083:8080"
    
  notifications-init-db:
    container_name: notifications-init-db
    image: postgres:12.4
    command: bash -c "chmod +x /tmp/notifications-init-db-sh && /tmp/notifications-init-db-sh"
    volumes:
      - ./notifications-init-db-sh:/tmp/notifications-init-db-sh
    env_file:
      - /home/rocky/tmp/kprice/tapisrc1-primary-data/notifications/env
    networks: 
      - tapis
    depends_on:
      notifications-postgres:
        condition: service_healthy

  notifications-postgres:
    container_name: notifications-postgres
    image: postgres:12.4
    environment:
      - PGDATA=/pgdata/data
    env_file:
      - /home/rocky/tmp/kprice/tapisrc1-primary-data/notifications/env
    networks: 
      - tapis
    volumes:
      - /home/rocky/tmp/kprice/tapisrc1-primary-data/notifications/postgres:/pgdata
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]

#  notifications-pgadmin:
#    container_name: notifications-pgadmin
#    image: dpage/pgadmin4:6.20
#    environment:
#      - PGADMIN_DEFAULT_EMAIL=wow@example.com
#    env_file:
#      - /home/rocky/tmp/kprice/tapisrc1-primary-data/notifications/env
#    networks:
#      - tapis
#    depends_on:
#      notifications-postgres:
#        condition: service_healthy
#      notifications-rabbitmq:
#        condition: service_healthy

  notifications-dispatcher:
    container_name: notifications-dispatcher
    image: tapis/notifications-dispatcher:1.6.2
    environment:
      - TAPIS_SITE_ID=tacc
      - TAPIS_TENANT_SVC_BASEURL=https://admin.rc1.tapis.io
      - TAPIS_DB_JDBC_URL=jdbc:postgresql://notifications-postgres:5432/tapisntfdb
      - TAPIS_DB_USER=tapis_ntf
      - TAPIS_QUEUE_HOST=notifications-rabbitmq
      - TAPIS_QUEUE_ADMIN_USER=tapis
      - TAPIS_QUEUE_USER=notif
    env_file:
      - /home/rocky/tmp/kprice/tapisrc1-primary-data/notifications/env
    networks:
      - tapis
    command: java -Xms1g -Xmx4g --add-opens java.base/java.lang=ALL-UNNAMED --add-opens java.base/java.time=ALL-UNNAMED --add-opens java.base/java.util=ALL-UNNAMED -cp "notifications.jar:dependencies/*" edu.utexas.tacc.tapis.notifications.DispatchApplication
    depends_on:
      notifications-postgres:
        condition: service_healthy
      notifications-rabbitmq:
        condition: service_healthy

  notifications-rabbitmq:
    container_name: notifications-rabbitmq
    image: rabbitmq:3.8.11-management
    environment:
      - HOSTNAME=notifications-rabbitmq
      - RABBITMQ_HOSTNAME=notifications-rabbitmq
      - RABBITMQ_DEFAULT_USER=tapis
      - RABBITMQ_VM_MEMORY_HIGH_WATERMARK=2147483648
    env_file: 
      - /home/rocky/tmp/kprice/tapisrc1-primary-data/notifications/env
    volumes:
      - /home/rocky/tmp/kprice/tapisrc1-primary-data/notifications/notifications-rabbitmq-data:/var/lib/rabbitmq/mnesia
    networks:
      - tapis
    healthcheck:
      test: rabbitmq-diagnostics check_running
