#!/bin/bash

echo "burnup authenticator:"

mkdir -p /home/rocky/tmp/kprice/tapisrc1-primary-data/authenticator
mkdir -p /home/rocky/tmp/kprice/tapisrc1-primary-data/authenticator/postgres
mkdir -p /home/rocky/tmp/kprice/tapisrc1-primary-data/authenticator/api
mkdir -p /home/rocky/tmp/kprice/tapisrc1-primary-data/authenticator/ldap

python3 ../admin/util/parse_skexport -c authenticator -d /home/rocky/tmp/kprice/tapisrc1-primary-data

docker compose up -d

