restheart-server-config.properties: |-
  ## RESTHeart Configuration - development properties.
  ## See: https://restheart.org/learn/configuration
  
  https-listener = false
  https-host = 0.0.0.0
  https-port = 4443
  http-listener = true
  http-host = 0.0.0.0
  http-port = 8080
  
  ajp-listener = true
  ajp-host = 0.0.0.0
  ajp-port = 8009
  
  instance-name = restheart-core
  
  #### Can be STANDARD, HAL or SHAL (aka PLAIN_JSON)
  
  default-representation-format = STANDARD
  # leave commented, get value from MONGO_URI environment var
  # mongo-uri = mongodb://restheart:some_password@restheart-mongo:27017/?authSource=admin
  
  # The MongoDb resource to bind to the root URI /
  # The format is /db[/coll[/docid]] or '*' to expose all dbs
  
  root-mongo-resource = '*'
  log-level = DEBUG
  # requests-log-level = 2
  query-time-limit = 0
  aggregation-time-limit = 0
  
  #suggested value: core*2
  
  io-threads=2
  
  #suggested value: core*16
  
  worker-threads=16
restheart-security-config.properties: |-
  instance-name=metav3-security
  
  # http://127.0.0.1:8080
  # restheart-proxy-pass=ajp://192.168.1.242:8009
  
  restheart-proxy-pass=ajp://restheart:8009
  http-host=0.0.0.0
  http-port=8080
  log-level=ALL
  requests-log-level=2
  ping-hello-message=Hello from MetaV3 Security!
  #serviceToken=get_from_secrets
  tokenHeader=X-Tapis-Token
  securityKernalEndPoint=https://https://admin.rc1.tapis.io/v3/security
  
  #suggested value: core*2
  io-threads=2
  #suggested value: core*16
  worker-threads=16