#!/bin/bash

echo "burnup security:"

mkdir -p /home/rocky/tmp/kprice/tapisrc1-primary-data/security
mkdir -p /home/rocky/tmp/kprice/tapisrc1-primary-data/security/postgres

python3 ../admin/util/parse_skexport -c security -d /home/rocky/tmp/kprice/tapisrc1-primary-data

docker compose up -d

