#!/bin/bash

echo "burnup tokens:"

# Read secrets from env file
mkdir -p /home/rocky/tmp/kprice/tapisrc1-primary-data/tokens
MYUID=`id -u`
docker run -it --rm -v /home/rocky/tmp/kprice/tapisrc1-primary-data/tokens:/tokens tapis/ubutil2204:1.6.0 chown $MYUID /tokens
python3 ../admin/util/parse_skexport -c tokens -d /home/rocky/tmp/kprice/tapisrc1-primary-data

docker compose up -d

