
networks:
    tapis:
        name: tapis
        external: true


services:
    jobs-api:
        container_name: jobs-api
        networks:
          - tapis
        image: tapis/jobsapi:1.6.3
        environment:
            - TAPIS_LOCAL_NODE_NAME=rc1.tapis.io
            - TAPIS_SITE_ID=tacc
            - TAPIS_TENANT_SVC_BASEURL=https://admin.rc1.tapis.io
            - TAPIS_DB_CONNECTION_POOL_SIZE=10
            - TAPIS_DB_USER=tapis
            - TAPIS_DB_JDBC_URL=jdbc:postgresql://jobs-postgres:5432/tapisjobsdb
            - TAPIS_QUEUE_HOST=jobs-rabbitmq
            - TAPIS_QUEUE_ADMIN_USER=tapis
            - TAPIS_QUEUE_USER=jobs
            - TAPIS_REQUEST_LOGGING_FILTER_PREFIXES=/v3/jobs
            - TAPIS_REQUEST_LOGGING_INGORE_SUFFIXES=/healthcheck;/ready;/hello
            - CATALINA_OPTS=-Xms1g -Xmx3g --add-opens java.base/java.time=ALL-UNNAMED
        env_file:
            - /home/rocky/tapisrc1-primary-data/jobs/env
        depends_on:
            jobs-migrations:
                condition: service_completed_successfully
            jobs-rabbitmq:
                condition: service_healthy
        ports: 
            - "8082:8080"
    
    jobs-postgres:
        container_name: jobs-postgres
        networks:
            - tapis
        image: postgres:12.4
        environment:
            - PGDATA=/pgdata/data
        env_file:
            - /home/rocky/tapisrc1-primary-data/jobs/env
        volumes:
            - /home/rocky/tapisrc1-primary-data/jobs/postgres:/pgdata
        healthcheck:
            test: pg_isready -U postgres
    
    jobs-migrations:
        container_name: jobs-migrations
        networks: 
            - tapis
        image: tapis/jobsmigrate:1.6.3
        environment:
            - HOST=jobs-postgres
            - PORT=5432
            - USER=postgres
        env_file:
            - /home/rocky/tapisrc1-primary-data/jobs/env
        depends_on:
            jobs-postgres:
                condition: service_healthy

    # jobs-pgadmin:
    #     container_name: jobs-pgadmin
    #     image: postgres:12.4
    #     environment:
    #         - PGDATA=/pgdata/data
    #     env_file:
    #         - /home/rocky/tapisrc1-primary-data/jobs/env
    #     volumes:
    #         - /home/rocky/tapisrc1-primary-data/jobs/jobs-pg-data:/pgdata

    jobs-rabbitmq:
        container_name: jobs-rabbitmq
        image: rabbitmq:3.8.11-management 
        environment:
            - HOSTNAME=jobs-rabbitmq
            - RABBITMQ_HOSTNAME=jobs-rabbitmq
            - RABBITMQ_DEFAULT_USER=tapis
            - RABBITMQ_VM_MEMORY_HIGH_WATERMARK=2147483648
        env_file:
            - /home/rocky/tapisrc1-primary-data/jobs/env
        volumes:
            - /home/rocky/tapisrc1-primary-data/jobs/jobs-rabbitmq-data:/var/lib/rabbitmq/mnesia
        networks:
            - tapis
        healthcheck:
            test: rabbitmq-diagnostics -q ping

    jobs-altqueue:
        container_name: jobs-altqueue
        image: tapis/jobsworker:1.6.3
        networks:
            - tapis
        environment:
            - TAPIS_SITE_ID=tacc
            - TAPIS_TENANT_SVC_BASEURL=https://admin.rc1.tapis.io
            - TAPIS_DB_CONNECTION_POOL_SIZE=2
            - TAPIS_DB_USER=tapis
            - TAPIS_DB_JDBC_URL=jdbc:postgresql://jobs-postgres:5432/tapisjobsdb
            - TAPIS_QUEUE_HOST=jobs-rabbitmq
            - TAPIS_QUEUE_ADMIN_USER=tapis
            - TAPIS_QUEUE_USER=jobs
            - TAPIS_REQUEST_LOGGING_FILTER_PREFIXES=/v3/jobs
            - JAVA_OPTS=-Xms1g -Xmx1g
            - MAIN_CLASS=edu.utexas.tacc.tapis.jobs.reader.AltQueueReader
            - JOBS_PARMS=-n rdr-alt
        env_file:
            - /home/rocky/tapisrc1-primary-data/jobs/env
        depends_on:
            jobs-migrations:
                condition: service_completed_successfully
            jobs-rabbitmq:
                condition: service_healthy

    jobs-recovery:
        container_name: jobs-recovery
        image: tapis/jobsworker:1.6.3
        environment:
            - TAPIS_SITE_ID=tacc
            - TAPIS_TENANT_SVC_BASEURL=https://admin.rc1.tapis.io
            - TAPIS_DB_CONNECTION_POOL_SIZE=2
            - TAPIS_DB_USER=tapis
            - TAPIS_DB_JDBC_URL=jdbc:postgresql://jobs-postgres:5432/tapisjobsdb
            - TAPIS_QUEUE_HOST=jobs-rabbitmq
            - TAPIS_QUEUE_ADMIN_USER=tapis
            - TAPIS_QUEUE_USER=jobs
            - TAPIS_REQUEST_LOGGING_FILTER_PREFIXES=/v3/jobs
            - JAVA_OPTS=-Xms1g -Xmx1g
            - MAIN_CLASS=edu.utexas.tacc.tapis.jobs.reader.RecoveryReader
            - JOBS_PARMS=-n rdr-recovery
        env_file:
            - /home/rocky/tapisrc1-primary-data/jobs/env
        networks: 
            - tapis
        depends_on:
            jobs-migrations:
                condition: service_completed_successfully
            jobs-rabbitmq:
                condition: service_healthy

    jobs-deadletter:
        container_name: jobs-deadletter
        image: tapis/jobsworker:1.6.3
        environment:
            - TAPIS_SITE_ID=tacc
            - TAPIS_TENANT_SVC_BASEURL=https://admin.rc1.tapis.io
            - TAPIS_DB_CONNECTION_POOL_SIZE=2
            - TAPIS_DB_USER=tapis
            - TAPIS_DB_JDBC_URL=jdbc:postgresql://jobs-postgres:5432/tapisjobsdb
            - TAPIS_QUEUE_HOST=jobs-rabbitmq
            - TAPIS_QUEUE_ADMIN_USER=tapis
            - TAPIS_QUEUE_USER=jobs
            - TAPIS_REQUEST_LOGGING_FILTER_PREFIXES=/v3/jobs
            - JAVA_OPTS=-Xms1g -Xmx1g
            - MAIN_CLASS=edu.utexas.tacc.tapis.jobs.reader.DeadLetterReader
            - JOBS_PARMS=-n rdr-dead
        env_file:
            - /home/rocky/tapisrc1-primary-data/jobs/env
        networks: 
            - tapis
        depends_on:
            jobs-migrations:
                condition: service_completed_successfully
            jobs-rabbitmq:
                condition: service_healthy

    jobs-eventqueue:
        container_name: jobs-eventqueue
        image: tapis/jobsworker:1.6.3
        environment:
            - TAPIS_SITE_ID=tacc
            - TAPIS_TENANT_SVC_BASEURL=https://admin.rc1.tapis.io
            - TAPIS_DB_CONNECTION_POOL_SIZE=2
            - TAPIS_DB_USER=tapis
            - TAPIS_DB_JDBC_URL=jdbc:postgresql://jobs-postgres:5432/tapisjobsdb
            - TAPIS_QUEUE_HOST=jobs-rabbitmq
            - TAPIS_QUEUE_ADMIN_USER=tapis
            - TAPIS_QUEUE_USER=jobs
            - TAPIS_REQUEST_LOGGING_FILTER_PREFIXES=/v3/jobs
            - JAVA_OPTS=-Xms1g -Xmx1g
            - MAIN_CLASS=edu.utexas.tacc.tapis.jobs.reader.EventReader
            - JOBS_PARMS=-n rdr-event
        env_file:
            - /home/rocky/tapisrc1-primary-data/jobs/env
        networks: 
            - tapis
        depends_on:
            jobs-migrations:
                condition: service_completed_successfully
            jobs-rabbitmq:
                condition: service_healthy

    jobs-workers:
        container_name: jobs-workers
        image: tapis/jobsworker:1.6.3
        environment:
            - TAPIS_LOCAL_NODE_NAME=rc1.tapis.io
            - TAPIS_SITE_ID=tacc
            - TAPIS_TENANT_SVC_BASEURL=https://admin.rc1.tapis.io
            - TAPIS_DB_CONNECTION_POOL_SIZE=10
            - TAPIS_DB_USER=tapis
            - TAPIS_DB_JDBC_URL=jdbc:postgresql://jobs-postgres:5432/tapisjobsdb
            - TAPIS_QUEUE_HOST=jobs-rabbitmq
            - TAPIS_QUEUE_ADMIN_USER=tapis
            - TAPIS_QUEUE_USER=jobs
            - TAPIS_REQUEST_LOGGING_FILTER_PREFIXES=/v3/jobs
            - JAVA_OPTS=-Xms1g -Xmx1g
            - MAIN_CLASS=edu.utexas.tacc.tapis.jobs.worker.JobWorker
            - JOBS_PARMS=-n wkr-DefaultQueue -q tapis.jobq.submit.DefaultQueue -w 100
        env_file:
            - /home/rocky/tapisrc1-primary-data/jobs/env
        networks:
            - tapis
        depends_on:
            jobs-migrations:
                condition: service_completed_successfully
            jobs-rabbitmq:
                condition: service_healthy
