#!/bin/bash

echo "burnup proxy:"

mkdir -p /home/rocky/tmp/kprice/tapisrc1-primary-data/proxy
mkdir -p /home/rocky/tmp/kprice/tapisrc1-primary-data/proxy/proxy-site-router-redis

docker compose up -d

