#!/bin/bash

echo "burnup systems:"

mkdir -p /home/rocky/tmp/kprice/tapisrc1-primary-data/systems
mkdir -p /home/rocky/tmp/kprice/tapisrc1-primary-data/systems/postgres

#MYUID=`id -u`
#docker run -it --rm -v /home/rocky/tmp/kprice/tapisrc1-primary-data/systems:/systems tapis/ubutil2204:1.6.1 chown $MYUID /systems

#export UID_GID="$(id -u):$(id -g)"

python3 ../admin/util/parse_skexport -c systems -d /home/rocky/tmp/kprice/tapisrc1-primary-data

docker compose up -d

