networks:
    tapis:
        name: tapis
        external: true

services:
    systems-api:
        container_name: systems-api
        image: tapis/systems:1.6.3
        networks:
            - tapis
        env_file:
            /home/rocky/tapisrc1-primary-data/systems/env
        environment:
            - TAPIS_DB_JDBC_URL=jdbc:postgresql://systems-postgres:5432/tapissysdb
            - TAPIS_SITE_ID=tacc
            - TAPIS_TENANT_SVC_BASEURL=https://admin.rc1.tapis.io
            - TAPIS_GLOBUS_CLIENT_ID
            - TAPIS_DB_USER=tapis_sys
        command: java -Xms1G -Xmx3G --add-opens java.base/java.lang=ALL-UNNAMED --add-opens java.base/java.time=ALL-UNNAMED --add-opens java.base/java.util=ALL-UNNAMED -cp "systems.jar:dependencies/*" edu.utexas.tacc.tapis.systems.api.SystemsApplication
        depends_on:
            systems-migrations:
                condition: service_completed_successfully
        ports: 
            - "8084:8080"
            
    systems-postgres:
        container_name: systems-postgres
        image: postgres:12.4
        networks:
            - tapis
        env_file:
            /home/rocky/tapisrc1-primary-data/systems/env
        environment:
            - PGDATA=/pgdata/data
        volumes:
            - /home/rocky/tapisrc1-primary-data/systems/postgres:/pgdata
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres"]

    systems-migrations:
        container_name: systems-migrations
        image: postgres:12.4
        networks:
            - tapis
        volumes:
            - ./systems-init-db-sh:/init-db
        env_file:
            /home/rocky/tapisrc1-primary-data/systems/env
        command: bash -c "cp /init-db /local_initdb && echo 100 && chown $(whoami) /local_initdb && echo 200 && chmod +x /local_initdb && echo 300 && /local_initdb"
        depends_on:
            systems-postgres:
                condition: service_healthy
